### PR TITLE
Feature/refactor nine thousand

### PR DESCRIPTION
**Pull request by wwwtyro**

### CODE REVIEW

**Comment by wwwtyro** [comment]
Add docstrings to all the things.

**Comment by tgjonestx** [comment]
+1 for docstrings on all classes

**Comment by tgjonestx** [comment]
I was able to run the example standalone, but had problems when I tried to run it in serviced.
```
$ serviced service migrate Zope ../service-migration/example.py 
407sgfccgckx782e37drudr6w: migration failed: could not unmarshall new service definition: json: cannot unmarshal array into Go value of type float64 
```
I _think_ the only float64 values are in HealthChecks. If you try a script as simple as
```
import servicemigration as sm
sm.require("1.0.0")

# Get the service context.
ctx = sm.ServiceContext()
ctx.commit()
```
Then look for Healthchecks in the output you'll see something like:
```
        "HealthChecks": {
            "answering": {
                "Interval": 10, 
                "Script": "curl -o /dev/null -w '%{redirect_url}' -s http://localhost:9080/zport/dmd | grep -q acl_users", 
                "Timeout": [
                    "Timeout"
                ]
            }, 
```

**Comment by tgjonestx** [comment]
:+1:

**Pull request merged**
